#!/bin/sh

until [ "$host_name" != "" ]; do
  DIALOG=${DIALOG=dialog}
  hostname_file=`tempfile 2>/dev/null` || hostname_file=/tmp/test$$
  trap "rm -f $hostname_file" 0 1 2 5 15

  $DIALOG --title "Hostname" --clear \
          --inputbox "Please enter the hostname. You must set a hostname to continue, however it can be changed post installation." 16 51 2> $hostname_file
  host_name=`cat $hostname_file`

  retval=$?

  case $retval in
    0)
      #echo "Input string is `cat $hostname_file`";;
      ;;
    1)
      #echo "Cancel pressed.";;
      ;;
    255)
      #if test -s $hostname_file ; then
      #  cat $hostname_file
      #else
      #  echo "ESC pressed."
      #fi
      ;;
  esac
done

until [ "$domain_name" != "" ]; do
  DIALOG=${DIALOG=dialog}
  domainname_file=`tempfile 2>/dev/null` || domainname_file=/tmp/test$$
  trap "rm -f $domainname_file" 0 1 2 5 15

  $DIALOG --title "Domain Name" --clear \
        --inputbox "Please enter the domain name. You must set a domain name to continue, however it can be changed post installation." 16 51 2> $domainname_file
  domain_name=`cat $domainname_file`
  retval2=$?

  case $retval2 in
    0)
      #echo "Input string is `cat $domainname_file`";;
      ;;
    1)
      #echo "Cancel pressed.";;
      ;;
    255)
      #if test -s $domainname_file ; then
      #  cat $domainname_file
      #else
      #  echo "ESC pressed."
      #fi
      ;;
  esac
done

#echo $host_name
#echo $domain_name
#echo $host_name.$domain_name

# set the hostname
/bin/sed -i "s/core/$host_name/g" /etc/hostname

# set the fqdn 
/bin/sed -i "s/core/$host_name.$domain_name $host_name/g" /etc/hosts

# Add your domain to the config files, to stop abuse of mailsystem
/usr/sbin/postconf -e "myorigin = $domain_name"

# Add your hostname 
/usr/sbin/postconf -e "myhostname = $host_name"

# Now add the domain names that your system will handle
/usr/sbin/postconf -e "relay_domains = $domain_name"

# reload postfix
#/etc/init.d/postfix reload
