#!/bin/sh
# activate selinux
# /usr/sbin/selinux-activate

# reboot required during configuration
# /sbin/reboot

# fix for "FSCKFIX is not enabled - not serious, but could prevent system from booting..." 
# /bin/sed -i "s/#FSCKFIX=no/FSCKFIX=yes/g" /etc/default/rcS

