#!/bin/sh
# This does not prevent it showing on first-boot, but afterwards it not longer appears.
# May need adding elsewhere to prevent on first-boot.
/etc/init.d/confconsole stop
/usr/sbin/update-rc.d -f confconsole remove

