#!/usr/bin/env python

"""
copyright 2013 neontribe ltd neil@neontribe.co.uk


a simple program to manage which linked data sources are used on this system

"""

from dialog import Dialog
import os


def main():
    dialog = Dialog()
    
    #find out what we data sources are in use
    using = {}
    using['eldis'] = 'on' if os.path.exists('/home/eldis/active') else 'off'
    using['r4d'] = 'on' if os.path.exists('/home/r4d/active') else 'off'
    
    text = """choose which data sources to use on this server
    """
    choices = [('eldis', 'use edlis data', using['eldis']),
               ('r4d', 'use r4d data', using['r4d'])]
    data_sources_to_use = dialog.checklist(text, choices=choices)
    if data_sources_to_use[0] == 0:
        #add eldis data
        if not os.path.exists('/home/eldis/active') and 'eldis' in data_sources_to_use[1]:
            os.system('python /usr/lib/inithooks/bin/use_eldis.py')
        #remove eldis
        if os.path.exists('/home/eldis/active') and 'eldis' not in data_sources_to_use[1]:
            os.system('rm -rf /home/eldis')
            #get virtuoso password
            fh = open('/etc/virtuoso-opensource-6.1/password', 'r')
            password = fh.read()
            fh.close()
            os.system("isql-vt 1111 dba " + password + " /opt/tools/eldis_remove.isql")
            os.system('rm -f /etc/cron.d/eldis')
        #add r4d data
        if not os.path.exists('/home/r4d/active') and 'r4d' in data_sources_to_use[1]:
            os.system('python /usr/lib/inithooks/bin/use_r4d.py')
        #remove r4d
        if os.path.exists('/home/r4d/active') and 'r4d' not in data_sources_to_use[1]:
            os.system('rm -rf /home/r4d')
            #get virtuoso password
            fh = open('/etc/virtuoso-opensource-6.1/password', 'r')
            password = fh.read()
            fh.close()
            os.system("isql-vt 1111 dba " + password + " /opt/tools/r4d_remove.isql")
            os.system('rm -f /etc/cron.d/r4d')
        
if __name__ == "__main__":
    main()