#!/bin/bash -ex
install()
{
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

# installing linked-data server packages
install apache2 openjdk-6-jre openssh-server php5 python2.6 virtuoso-opensource virtuoso-vad-conductor virtuoso-vad-isparql wget

# tell the world what we've done!
echo 'Added apache2 openjdk openssh-server php python virtuoso wget' >> /etc/issue
