parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: sy2_linked_data
    database_user: sy2_linked_data
    database_password: FOO
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 4c56519106918998192c9558f3bb8ab50
    database_path: null

    # sparql_endpoint: http://public5.neontribe.co.uk/ld/eldis/sparql
    # sparql_endpoint: http://localhost:8890/sparql
    sparql_endpoint: http://ld.neontribe.org/sparql
    # sparql_endpoint: http://192.168.21.138:8890/sparql
