#!/bin/bash -ex
# executed after apply-overlay

# setting up apache for sparql and snorql
a2enmod auth_digest proxy_http rewrite
a2ensite sparql custom_sparql_endpoints lodspeakr

# clean up apache
rm /var/www/index.html


#load test eldis data into virtuoso

#get data to where it is needed
#python /opt/tools/eldis_crawl.py 


#note we cannot do this here as virtuoso will not start in the chrooted patch environment
#so we should do it on first boot
#isql-vt -H localhost -S 1111 -U dba -P dba < /opt/tools/eldis_load.isql

# tell the world what we've done!
echo 'Welcome to the Linked-Development appliance' >> /etc/issue

#setup virtuoso install
ln -s /opt/virtuoso6/bin/isql /usr/bin/isql-vt
mkdir -p /var/lib/virtuoso-opensource-6.1/db/
mkdir -p /var/log/virtuoso-opensource-6.1/
echo 'PATH=/opt/virtuoso6/bin:$PATH' >> /root/.bashrc

#setup lodspeakr permissions
#lodspeakr removed into separate package so this fails, ensure this is done as part of the lodspeakr install
#chmod 777 -R /var/www/htdocs/lodspeakr/cache /var/www/htdocs/lodspeakr/meta

#setup virtuoso start/stopln -s /etc/init.d/virtuoso-opensource-6.1 /etc/rc2.d/S80virtuoso 
update-rc.d virtuoso-opensource-6.1 start NN 2 3 4 5  . stop NN 0 1 6 .

#symlink /opt/openapi/web to /var/www/htdocs/openapi
#ln -s /opt/openapi/web /var/www/htdocs/openapi

#Install composer.phar (twice because it often fails first time)
#php /opt/openapi/app/composer.phar --working-dir=/opt/openapi update
#php /opt/openapi/app/composer.phar --working-dir=/opt/openapi update

# clear the composer logs
#rm -rf /opt/openapi/app/{cache,logs}/*

# reset permissions
#chown -R nobody:nogroup /opt/openapi
#chown -R www-data:www-data /opt/openapi/app/{logs,cache}
#chmod -R 1775 /opt/openapi/app/{logs,cache}

# Add dotdebs php54 backport
echo "# dotdebs backports and php54" >> /etc/apt/sources.list.d/sources.list
echo "deb http://packages.dotdeb.org squeeze all" >> /etc/apt/sources.list.d/sources.list
echo "deb-src http://packages.dotdeb.org squeeze all" >> /etc/apt/sources.list.d/sources.list
echo "deb http://packages.dotdeb.org squeeze-php54 all" >> /etc/apt/sources.list.d/sources.list
echo "deb-src http://packages.dotdeb.org squeeze-php54 all" >> /etc/apt/sources.list.d/sources.list
apt-key add /etc/apt/sources.list.d/dotdeb.gpg
rm /etc/apt/sources.list.d/dotdeb.gpg
apt-get update
apt-get -y -t squeeze-backports install php5

