#!/bin/bash -ex
# executed before apply-overlay

# source our custom functions
cwd=$(dirname $0)
source $cwd/functions

# Install packages
# removed selinux-basics selinux-policy-default as they broke wheezy RC
install apache2 openjdk-6-jre openssh-server php5 postfix python2.6  wget python-pip selinux-basics selinux-policy-default curl sqlite3 php5-curl php5-sqlite



pip install rdflib>3.1

# Report on installation.
echo 'Added apache2 openjdk-6-jre openssh-server php5 postfix python2.6 wget python-pip selinux-basics selinux-policy-default' >> /etc/issue
