#!/bin/bash
# Configure postfix
# Currently does nothing, it's possible we could prompt for 
# domain, hostname and relay domains, they may want to be fixed

# Add your domain to the config files, to stop abuse of mailsystem
# /usr/sbin/postconf -e "myorigin = example.com"

# Add your hostname 
# /usr/sbin/postconf -e "myhostname = server1.example.com"

# Now add the domain names that your system will handle
# /usr/sbin/postconf -e "relay_domains = example.com, example2.com"

# reload postfix
# /usr/sbin/postfix reload
